/**
 * PROPERTYNEX — OTP password-recovery integration tests.
 *
 * These run against a real running dev server and a real MongoDB, over real
 * HTTP. Nothing is mocked: passcodes are generated by the server, hashed into
 * the database, and read back out of the development console provider's output
 * the same way a developer would read them.
 *
 *   node --env-file=.env --test tests/integration/otp-flow.test.mjs
 *
 * Requires:
 *   BASE_URL       base URL of a running `next dev` server
 *   DEV_LOG_PATH   file the dev server's stdout is being written to
 *
 * Two conditions are load-bearing and asserted rather than assumed: the server
 * must be in development mode (the console provider refuses to run in
 * production), and the log file must exist.
 *
 * Note on rate limits: the flow's own limiters are in-process and generous
 * enough for one pass of this suite (6 `start` calls against a budget of 8/IP
 * per 10 minutes, 5 signups against 8/minute). Running the suite twice inside
 * ten minutes without restarting the server will legitimately hit 429s.
 */
import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PrismaClient } from "@prisma/client";

const BASE_URL = process.env.BASE_URL ?? "http://127.0.0.1:3100";
const LOG_PATH = process.env.DEV_LOG_PATH ?? "dev-server.log";

const prisma = new PrismaClient();

/** Every response body seen, so we can prove no passcode ever appeared in one. */
const allResponseBodies = [];
/** Every passcode the server generated during this run. */
const allCodes = [];
/** Test accounts created here, cleaned up at the end. */
const createdUserIds = [];
/** Wall-clock start, used to scope decoy-session cleanup. */
const suiteStartedAt = Date.now();

let logOffset = 0;

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function uniqueSuffix() {
  // Distinct per user, and distinct across runs, without needing randomness
  // that could collide inside one second.
  counter += 1;
  return `${Date.now().toString().slice(-8)}${String(counter).padStart(2, "0")}`;
}
let counter = 0;

/**
 * Distinct client IP for this suite.
 *
 * `getClientIp` honours `x-forwarded-for`, so sending one pins every request in
 * this suite to its own rate-limit buckets. That matters for two reasons: the
 * suite's budget is not consumed by anything else hitting the same dev server
 * (a browser tab, another developer), and the dedicated rate-limit test below
 * can exhaust a limiter without stranding the rest of the suite.
 */
const TEST_IP = "203.0.113.10";

async function api(path, { method = "POST", body, cookie, ip = TEST_IP } = {}) {
  const headers = { "x-forwarded-for": ip };
  if (body !== undefined) headers["Content-Type"] = "application/json";
  if (cookie) headers.cookie = cookie;

  const response = await fetch(`${BASE_URL}${path}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });

  const text = await response.text();
  allResponseBodies.push(text);

  let json = null;
  try {
    json = JSON.parse(text);
  } catch {
    // Non-JSON (e.g. an HTML error page) — surfaced via `text` in assertions.
  }

  return {
    status: response.status,
    json,
    text,
    setCookie: response.headers.getSetCookie?.() ?? [],
  };
}

/** Extracts the session cookie pair from a Set-Cookie list. */
function sessionCookie(setCookie) {
  const found = setCookie.find((value) => value.startsWith("propertynex_session="));
  return found ? found.split(";")[0] : null;
}

/** Reads whatever the dev server has logged since the last call. */
async function readNewLog() {
  const content = await readFile(LOG_PATH, "utf8").catch(() => "");
  const fresh = content.slice(logOffset);
  logOffset = content.length;
  return fresh;
}

/**
 * Waits for the console provider to print a passcode and returns it.
 *
 * Reading the code out of the server's own log is what keeps these tests
 * honest: the passcode is never returned over HTTP, so there is no way to
 * obtain it except the delivery channel, which is exactly the property being
 * tested.
 */
async function waitForCode(timeoutMs = 20_000) {
  const deadline = Date.now() + timeoutMs;
  let buffer = "";
  while (Date.now() < deadline) {
    buffer += await readNewLog();
    const matches = [...buffer.matchAll(/passcode:\s*(\d{6})/g)];
    if (matches.length > 0) {
      const code = matches[matches.length - 1][1];
      allCodes.push(code);
      return code;
    }
    await sleep(200);
  }
  throw new Error("timed out waiting for a passcode in the dev server log");
}

async function signup(label) {
  const suffix = uniqueSuffix();
  const account = {
    name: `Test ${label}`,
    email: `otptest.${label.toLowerCase()}.${suffix}@example.com`,
    phone: `+1 ${suffix.slice(0, 3)} ${suffix.slice(3, 6)} ${suffix.slice(6)}`,
    password: "InitialPass123",
  };

  const response = await api("/api/auth/signup", {
    body: {
      ...account,
      confirmPassword: account.password,
      acceptedTerms: true,
    },
  });

  assert.equal(response.status, 200, `signup failed for ${label}: ${response.text}`);
  account.id = response.json.user.id;
  account.cookie = sessionCookie(response.setCookie);
  createdUserIds.push(account.id);
  // Drain anything already in the log so the next waitForCode only sees codes
  // produced after this point.
  await readNewLog();
  return account;
}

// ─────────────────────────────────────────────────────────────
// Preconditions
// ─────────────────────────────────────────────────────────────

let usersBefore = 0;

test("preconditions: dev server reachable, in development mode, log readable", async () => {
  const response = await api("/api/auth/session", { method: "GET" });
  assert.equal(response.status, 200, `server not reachable at ${BASE_URL}`);

  const log = await readFile(LOG_PATH, "utf8").catch(() => null);
  assert.notEqual(log, null, `dev server log not readable at ${LOG_PATH}`);
  logOffset = log.length;

  usersBefore = await prisma.user.count();
  assert.ok(usersBefore >= 0);
});

// ─────────────────────────────────────────────────────────────
// 1. Baseline auth: signup / login / logout still work
// ─────────────────────────────────────────────────────────────

let userA;

test("signup creates an account and issues a session", async () => {
  userA = await signup("A");
  assert.ok(userA.id, "no user id returned");
  assert.ok(userA.cookie, "no session cookie set");

  const session = await api("/api/auth/session", { method: "GET", cookie: userA.cookie });
  assert.equal(session.status, 200);
  assert.equal(session.json.user.email, userA.email);
});

test("signup does not ask for or store a security question", async () => {
  const row = await prisma.user.findUnique({ where: { id: userA.id } });
  assert.equal(row.securityQuestionId, null, "signup still wrote a security question id");
  assert.equal(row.securityAnswerHash, null, "signup still wrote a security answer hash");
});

test("signup records phoneDigits for recovery lookups", async () => {
  const row = await prisma.user.findUnique({ where: { id: userA.id } });
  assert.equal(row.phoneDigits, userA.phone.replace(/\D/g, ""));
});

test("logout clears the session", async () => {
  const response = await api("/api/auth/logout", { cookie: userA.cookie });
  assert.equal(response.status, 200);

  const after = await api("/api/auth/session", { method: "GET", cookie: userA.cookie });
  assert.equal(after.status, 200);
  assert.equal(after.json.user, null, "session survived logout");
});

test("login works with the correct password", async () => {
  const response = await api("/api/auth/login", {
    body: { email: userA.email, password: userA.password },
  });
  assert.equal(response.status, 200);
  assert.ok(sessionCookie(response.setCookie), "login issued no session cookie");
});

test("login rejects a wrong password with a generic message", async () => {
  const response = await api("/api/auth/login", {
    body: { email: userA.email, password: "WrongPass123" },
  });
  assert.equal(response.status, 401);
  assert.equal(response.json.error, "Invalid email or password.");
});

// ─────────────────────────────────────────────────────────────
// 2. Account enumeration
// ─────────────────────────────────────────────────────────────

let realStart;
let decoyStart;
let decoyToken;

test("forgot-password/start answers identically for existing and non-existing accounts", async () => {
  realStart = await api("/api/auth/forgot-password/start", {
    body: { identifier: userA.email },
  });
  const codeForA = await waitForCode();
  assert.match(codeForA, /^\d{6}$/);
  userA.code = codeForA;

  decoyStart = await api("/api/auth/forgot-password/start", {
    body: { identifier: `definitely.not.a.user.${uniqueSuffix()}@example.com` },
  });
  decoyToken = decoyStart.json.recoveryToken;

  assert.equal(realStart.status, 200);
  assert.equal(decoyStart.status, 200, "unknown identifier got a different status");
  assert.deepEqual(
    Object.keys(realStart.json).sort(),
    Object.keys(decoyStart.json).sort(),
    "response shape differs between existing and non-existing accounts"
  );

  // Every field except the opaque token and the echoed-back mask must match.
  for (const key of ["channel", "codeLength", "expiresInSeconds", "resendAfterSeconds", "resendsRemaining", "maxAttempts"]) {
    assert.deepEqual(
      realStart.json[key],
      decoyStart.json[key],
      `field "${key}" differs between existing and non-existing accounts`
    );
  }
  assert.notEqual(realStart.json.recoveryToken, decoyStart.json.recoveryToken);
});

test("a non-existing account still gets a real, persisted recovery session", async () => {
  // This is what makes step 2 indistinguishable: a decoy token that was never
  // stored would produce "session expired" here instead of "wrong code".
  const response = await api("/api/auth/forgot-password/verify-otp", {
    body: { recoveryToken: decoyToken, code: "000000" },
  });
  assert.equal(response.status, 401, `decoy session behaved differently: ${response.text}`);
  assert.equal(response.json.fieldErrors.code, "INCORRECT_CODE");
  assert.match(response.json.error, /not correct/i);
});

test("no response ever reveals that an account does not exist", () => {
  const joined = allResponseBodies.join("\n").toLowerCase();
  for (const phrase of [
    "no account",
    "not found",
    "does not exist",
    "doesn't exist",
    "unknown user",
    "no user",
  ]) {
    assert.ok(!joined.includes(phrase), `a response leaked the phrase "${phrase}"`);
  }
});

test("an unparseable identifier is reported plainly (format, not existence)", async () => {
  const response = await api("/api/auth/forgot-password/start", {
    body: { identifier: "notanemail" },
  });
  assert.equal(response.status, 400);
  assert.ok(response.json.fieldErrors.identifier, "no field error for a malformed identifier");
});

// ─────────────────────────────────────────────────────────────
// 3. Passcode verification: wrong, right, replayed
// ─────────────────────────────────────────────────────────────

let resetTokenA;

test("an incorrect passcode is rejected and reports the remaining budget", async () => {
  const wrong = userA.code === "000000" ? "111111" : "000000";
  const response = await api("/api/auth/forgot-password/verify-otp", {
    body: { recoveryToken: realStart.json.recoveryToken, code: wrong },
  });
  assert.equal(response.status, 401);
  assert.equal(response.json.fieldErrors.code, "INCORRECT_CODE");
  assert.match(response.json.error, /\d+ attempts? left/);
});

test("the incorrect attempt was recorded against the session", async () => {
  const row = await prisma.passwordResetSession.findFirst({
    where: { userId: userA.id, used: false },
  });
  assert.equal(row.otpAttempts, 1);
});

test("the correct passcode verifies and returns a reset token", async () => {
  const response = await api("/api/auth/forgot-password/verify-otp", {
    body: { recoveryToken: realStart.json.recoveryToken, code: userA.code },
  });
  assert.equal(response.status, 200, response.text);
  assert.ok(response.json.resetToken, "no reset token returned");
  resetTokenA = response.json.resetToken;
});

test("verification rotates the token, so the pre-verification one is dead", async () => {
  assert.notEqual(resetTokenA, realStart.json.recoveryToken, "token was not rotated");

  const response = await api("/api/auth/forgot-password/verify-otp", {
    body: { recoveryToken: realStart.json.recoveryToken, code: userA.code },
  });
  assert.equal(response.status, 400);
  assert.equal(response.json.fieldErrors.form, "EXPIRED_SESSION");
});

test("the passcode is one-time use — it is gone from the database after verifying", async () => {
  const row = await prisma.passwordResetSession.findFirst({
    where: { userId: userA.id, used: false },
  });
  assert.equal(row.stage, "OTP_VERIFIED");
  assert.equal(row.otpHash, null, "verified session still holds passcode material");
  assert.equal(row.otpExpiresAt, null);
});

test("replaying the passcode against the rotated token does not verify again", async () => {
  const response = await api("/api/auth/forgot-password/verify-otp", {
    body: { recoveryToken: resetTokenA, code: userA.code },
  });
  assert.notEqual(response.status, 200, "a spent passcode verified a second time");
  assert.equal(response.json.fieldErrors.form, "EXPIRED_SESSION");
});

// ─────────────────────────────────────────────────────────────
// 4. Password reset and login afterwards
// ─────────────────────────────────────────────────────────────

const NEW_PASSWORD = "BrandNewPass456";

test("the reset token sets a new password", async () => {
  const response = await api("/api/auth/forgot-password/reset", {
    body: {
      resetToken: resetTokenA,
      newPassword: NEW_PASSWORD,
      confirmPassword: NEW_PASSWORD,
    },
  });
  assert.equal(response.status, 200, response.text);
  assert.equal(response.json.success, true);
});

test("the reset token cannot be used a second time", async () => {
  const response = await api("/api/auth/forgot-password/reset", {
    body: {
      resetToken: resetTokenA,
      newPassword: "YetAnotherPass789",
      confirmPassword: "YetAnotherPass789",
    },
  });
  assert.equal(response.status, 400);
  assert.equal(response.json.fieldErrors.form, "EXPIRED_SESSION");
});

test("login works with the new password", async () => {
  const response = await api("/api/auth/login", {
    body: { email: userA.email, password: NEW_PASSWORD },
  });
  assert.equal(response.status, 200, response.text);
  assert.ok(sessionCookie(response.setCookie));
});

test("login with the old password now fails", async () => {
  const response = await api("/api/auth/login", {
    body: { email: userA.email, password: userA.password },
  });
  assert.equal(response.status, 401);
});

test("resetting the password revoked every existing session for that account", async () => {
  // One session survives: the login in the preceding test. What must be gone is
  // everything issued before the reset.
  const sessions = await prisma.session.count({ where: { userId: userA.id } });
  assert.equal(sessions, 1, `expected only the post-reset session, found ${sessions}`);
});

test("a weak new password is rejected by the reset endpoint", async () => {
  // Uses an already-spent token: validation runs before the session check, so
  // this exercises the password rules without consuming a fresh session.
  const response = await api("/api/auth/forgot-password/reset", {
    body: { resetToken: resetTokenA, newPassword: "short", confirmPassword: "short" },
  });
  assert.equal(response.status, 400);
  assert.ok(response.json.fieldErrors.newPassword, "weak password was not flagged");
});

// ─────────────────────────────────────────────────────────────
// 5. Expiry
// ─────────────────────────────────────────────────────────────

test("an expired passcode is rejected", async () => {
  const userB = await signup("B");
  const start = await api("/api/auth/forgot-password/start", {
    body: { identifier: userB.email },
  });
  assert.equal(start.status, 200);
  const code = await waitForCode();

  // Wind the passcode's expiry into the past rather than waiting ten minutes.
  // The session itself stays live, so this isolates code expiry from session
  // expiry.
  await prisma.passwordResetSession.updateMany({
    where: { userId: userB.id, used: false },
    data: { otpExpiresAt: new Date(Date.now() - 1000) },
  });

  const response = await api("/api/auth/forgot-password/verify-otp", {
    body: { recoveryToken: start.json.recoveryToken, code },
  });
  assert.equal(response.status, 400, response.text);
  assert.equal(response.json.fieldErrors.code, "EXPIRED_CODE");
  assert.match(response.json.error, /expired/i);
});

// ─────────────────────────────────────────────────────────────
// 6. Attempt limit
// ─────────────────────────────────────────────────────────────

test("too many incorrect passcodes locks the session out", async () => {
  const userC = await signup("C");
  const start = await api("/api/auth/forgot-password/start", {
    body: { identifier: userC.email },
  });
  assert.equal(start.status, 200);
  const code = await waitForCode();
  const token = start.json.recoveryToken;

  const wrongCodes = ["111111", "222222", "333333", "444444", "555555"].filter((c) => c !== code);

  for (let i = 0; i < 5; i += 1) {
    const response = await api("/api/auth/forgot-password/verify-otp", {
      body: { recoveryToken: token, code: wrongCodes[i] },
    });
    assert.equal(response.status, 401, `attempt ${i + 1} did not return 401: ${response.text}`);
  }

  // Sixth attempt is refused on budget, before the comparison happens.
  const exhausted = await api("/api/auth/forgot-password/verify-otp", {
    body: { recoveryToken: token, code: wrongCodes[0] },
  });
  assert.equal(exhausted.status, 429, exhausted.text);
  assert.equal(exhausted.json.fieldErrors.code, "ATTEMPTS_EXHAUSTED");

  // And the *correct* code is refused too — the budget is checked first, so a
  // locked-out session cannot be unlocked by finally guessing right.
  const correctButLocked = await api("/api/auth/forgot-password/verify-otp", {
    body: { recoveryToken: token, code },
  });
  assert.equal(correctButLocked.status, 429, correctButLocked.text);
  assert.equal(correctButLocked.json.fieldErrors.code, "ATTEMPTS_EXHAUSTED");
});

// ─────────────────────────────────────────────────────────────
// 7. Resend
// ─────────────────────────────────────────────────────────────

test("resend enforces a cooldown, then issues a new code that supersedes the old one", async () => {
  const userD = await signup("D");
  const start = await api("/api/auth/forgot-password/start", {
    body: { identifier: userD.email },
  });
  assert.equal(start.status, 200);
  const firstCode = await waitForCode();
  const token = start.json.recoveryToken;

  // Immediately after the initial send, resend is on cooldown.
  const tooSoon = await api("/api/auth/forgot-password/resend", {
    body: { recoveryToken: token },
  });
  assert.equal(tooSoon.status, 429, tooSoon.text);
  assert.equal(tooSoon.json.fieldErrors.form, "COOLDOWN");
  assert.match(tooSoon.json.error, /wait \d+s/);

  // Wind `lastSentAt` back rather than sleeping out the full 60s.
  await prisma.passwordResetSession.updateMany({
    where: { userId: userD.id, used: false },
    data: { lastSentAt: new Date(Date.now() - 61_000) },
  });

  const resent = await api("/api/auth/forgot-password/resend", {
    body: { recoveryToken: token },
  });
  assert.equal(resent.status, 200, resent.text);
  assert.equal(resent.json.resendsRemaining, 2);
  const secondCode = await waitForCode();
  assert.notEqual(secondCode, firstCode, "resend reissued the same passcode");

  // The superseded code must no longer work.
  const oldCode = await api("/api/auth/forgot-password/verify-otp", {
    body: { recoveryToken: token, code: firstCode },
  });
  assert.equal(oldCode.status, 401, `superseded passcode was accepted: ${oldCode.text}`);

  // The new one must.
  const newCode = await api("/api/auth/forgot-password/verify-otp", {
    body: { recoveryToken: token, code: secondCode },
  });
  assert.equal(newCode.status, 200, newCode.text);
});

// ─────────────────────────────────────────────────────────────
// 8. Mobile-number identifier
// ─────────────────────────────────────────────────────────────

test("recovery works by mobile number, including reformatted input", async () => {
  const userE = await signup("E");

  // Deliberately re-typed with different punctuation from what was registered.
  const digits = userE.phone.replace(/\D/g, "");
  const reformatted = `+${digits.slice(0, 1)}(${digits.slice(1, 4)})${digits.slice(4, 7)}-${digits.slice(7)}`;
  assert.notEqual(reformatted, userE.phone);

  const start = await api("/api/auth/forgot-password/start", {
    body: { identifier: reformatted },
  });
  assert.equal(start.status, 200, start.text);
  assert.equal(start.json.channel, "SMS", "phone identifier did not select the SMS channel");

  // A code arriving at all proves the reformatted number resolved to the account.
  const code = await waitForCode();
  const verified = await api("/api/auth/forgot-password/verify-otp", {
    body: { recoveryToken: start.json.recoveryToken, code },
  });
  assert.equal(verified.status, 200, verified.text);

  assert.ok(start.json.destination.endsWith(digits.slice(-4)), start.json.destination);
  assert.ok(!start.json.destination.includes(digits.slice(0, 6)), "masked number leaked too much");
});

// ─────────────────────────────────────────────────────────────
// 9. Rate limiting
// ─────────────────────────────────────────────────────────────

test("repeated requests for one identifier are rate limited", async () => {
  // Its own client IP so exhausting this budget does not affect the rest of the
  // suite, and a non-existent identifier so no real account's live session gets
  // churned. The per-identifier limiter is the security-relevant one: it is what
  // stops one account's recovery flow being hammered from many addresses.
  const ip = "203.0.113.99";
  const identifier = `ratelimit.probe.${uniqueSuffix()}@example.com`;

  const statuses = [];
  for (let i = 0; i < 5; i += 1) {
    const response = await api("/api/auth/forgot-password/start", {
      body: { identifier },
      ip,
    });
    statuses.push(response.status);
  }

  assert.deepEqual(
    statuses.slice(0, 4),
    [200, 200, 200, 200],
    `expected the first four requests to succeed, got ${statuses.join(",")}`
  );
  assert.equal(statuses[4], 429, `expected the fifth request to be limited, got ${statuses[4]}`);
});

// ─────────────────────────────────────────────────────────────
// 10. Passcode confidentiality
// ─────────────────────────────────────────────────────────────

test("no passcode ever appeared in an HTTP response body", () => {
  assert.ok(allCodes.length >= 5, `expected several codes to have been issued, got ${allCodes.length}`);
  const joined = allResponseBodies.join("\n");
  for (const code of allCodes) {
    // The code may legitimately appear in a body only because we echoed it
    // back in a *request*; bodies here are responses only.
    assert.ok(!joined.includes(code), `passcode ${code} appeared in a response body`);
  }
});

test("no passcode is stored in plaintext in the database", async () => {
  const rows = await prisma.passwordResetSession.findMany();
  assert.ok(rows.length > 0, "no recovery sessions found to inspect");
  const serialized = JSON.stringify(rows);
  for (const code of allCodes) {
    assert.ok(!serialized.includes(code), `passcode ${code} found in the database`);
  }
  for (const row of rows) {
    if (row.otpHash !== null) {
      assert.match(row.otpHash, /^[0-9a-f]{64}$/, "otpHash is not a sha256 hex digest");
    }
  }
});

// ─────────────────────────────────────────────────────────────
// 11. Existing data untouched
// ─────────────────────────────────────────────────────────────

test("pre-existing accounts were not disturbed", async () => {
  const total = await prisma.user.count();
  // `>=` rather than `==`: this suite may share its dev server with a browser
  // session, and someone signing up mid-run is not a failure of these changes.
  // What must hold is that nothing was destroyed.
  assert.ok(
    total >= usersBefore + createdUserIds.length,
    `user count dropped: ${total} < ${usersBefore} + ${createdUserIds.length}`
  );

  // Legacy rows keep their data; the security-question columns became optional,
  // they were not dropped, and nothing else was rewritten.
  const legacy = await prisma.user.findMany({
    where: { id: { notIn: createdUserIds } },
    select: { id: true, email: true, phone: true, passwordHash: true },
  });
  assert.equal(legacy.length, total - createdUserIds.length);
  for (const row of legacy) {
    assert.ok(row.email, "a pre-existing user lost its email");
    assert.ok(row.phone, "a pre-existing user lost its phone");
    assert.ok(row.passwordHash, "a pre-existing user lost its password hash");
  }
});

test("cleanup: remove accounts and decoy sessions created by this suite", async () => {
  await prisma.passwordResetSession.deleteMany({ where: { userId: { in: createdUserIds } } });
  await prisma.session.deleteMany({ where: { userId: { in: createdUserIds } } });
  const { count } = await prisma.user.deleteMany({ where: { id: { in: createdUserIds } } });
  assert.equal(count, createdUserIds.length);

  // Decoy sessions have no user to key on, so they are removed by age.
  await prisma.passwordResetSession.deleteMany({
    where: { userId: null, createdAt: { gte: new Date(suiteStartedAt) } },
  });

  await prisma.$disconnect();
});
