import { z } from "zod";
import {
  MAX_ALT_LENGTH,
  MAX_FILES_PER_UPLOAD,
  UPLOADABLE_KINDS,
  isUploadableKind,
} from "@/lib/media/constants";

/**
 * Server-side validation for media writes — the trust boundary for this feature.
 *
 * ── What is not here, and why ───────────────────────────────────────────────
 *
 * The same subtraction `lib/validation/property.ts` documents. There is no schema
 * field for `propertyId`, `ownerId`, `storageKey`, `storageDriver`, `mimeType`,
 * `byteSize`, `width`, `height` or `checksum`, so a client that posts them has
 * them stripped by Zod before anything reaches Prisma:
 *
 *   - `propertyId` comes from the URL, after `requireOwnedProperty` has proved the
 *     caller may write to that listing.
 *   - `ownerId` is copied from the property row the guard returned.
 *   - `storageKey` / `storageDriver` are generated by `lib/media/keys.ts` and the
 *     installed driver. A client-supplied key is the whole path-traversal class of
 *     bug; the schema has nowhere to put one.
 *   - `mimeType`, `byteSize`, `width`, `height`, `checksum` are *measured* from the
 *     bytes by `lib/media/image.ts`. Accepting a claimed MIME type or a claimed
 *     size would make every check downstream of it decorative.
 *
 * What is left is exactly the two things a client legitimately decides: the order
 * of the gallery, and which photo is the cover — plus optional alt text.
 */

/**
 * A media id in a request body.
 *
 * Shape-checked here so a hostile payload never reaches Prisma's Mongo connector,
 * which throws on a malformed ObjectId (`lib/properties/ownership.ts` explains the
 * 500-instead-of-404 that causes). Ids that are well-formed but belong to another
 * listing are handled a step later, by `lib/media/order.ts`, which ignores any id
 * that is not in the row set it was given.
 */
const mediaId = z.string().regex(/^[0-9a-fA-F]{24}$/, "That photo could not be found.");

/**
 * Owner-supplied alternative text.
 *
 * Trimmed, control characters stripped, capped. `""` becomes `null` rather than an
 * empty string: "no alt text provided" and "alt text that is deliberately empty"
 * are the same thing for a photo, and a nullable column says so more clearly than
 * a sentinel.
 */
const altText = z
  .string()
  .max(MAX_ALT_LENGTH * 4, `Keep the description under ${MAX_ALT_LENGTH} characters.`)
  .transform((value) =>
    value
      // eslint-disable-next-line no-control-regex
      .replace(/[\x00-\x1F\x7F-\x9F]/g, " ")
      .replace(/\s+/g, " ")
      .trim()
  )
  .pipe(z.string().max(MAX_ALT_LENGTH, `Keep the description under ${MAX_ALT_LENGTH} characters.`))
  .transform((value) => (value.length === 0 ? null : value));

/**
 * The `kind` field on an upload.
 *
 * Validated against `UPLOADABLE_KINDS` — one member — rather than against the
 * `MediaKind` enum, which has four. That is the mechanism that keeps the future
 * shape in the schema without shipping three unfinished features: a request for
 * `VIDEO` is refused at the boundary with a plain message, not half-handled.
 */
export const mediaKindSchema = z
  .string()
  .default("IMAGE")
  .refine(isUploadableKind, {
    message: `Only photos can be uploaded right now (accepted: ${UPLOADABLE_KINDS.join(", ")}).`,
  });

/**
 * The non-file fields of the multipart upload.
 *
 * `alt` is deliberately *not* one of them. An upload may carry ten files and a
 * multipart body has one `alt` field, so accepting it here would mean either
 * applying one description to ten different photos or inventing an indexing
 * convention (`alt[0]`, `alt[1]`, …) for a form that has no per-file text input
 * yet. Alt text is set per photo afterwards, through
 * `PATCH /api/properties/[id]/media/[mediaId]`, which is unambiguous.
 */
export const mediaUploadFieldsSchema = z.object({
  kind: mediaKindSchema,
});

/**
 * `PATCH /api/properties/[id]/media` — reorder, or set the cover, or both.
 *
 * Both fields are optional but at least one must be present: a PATCH that asks for
 * nothing is a client bug, and answering it with 200 would hide that bug. The
 * `order` array is capped generously — it is bounded by the per-property image
 * limit in practice, and the cap here only stops a caller posting a million ids to
 * make the server sort them.
 */
export const mediaArrangeSchema = z
  .object({
    order: z.array(mediaId).max(500, "That's more photos than this listing can hold.").optional(),
    primaryId: mediaId.optional(),
  })
  .refine((value) => value.order !== undefined || value.primaryId !== undefined, {
    message: "Nothing to change.",
  });

export type MediaArrangeInput = z.infer<typeof mediaArrangeSchema>;

/** `PATCH /api/properties/[id]/media/[mediaId]` — the per-photo fields. */
export const mediaUpdateSchema = z
  .object({
    alt: altText.optional(),
    /** `true` promotes this photo to cover. `false` is rejected rather than
     *  honoured: "not the cover" is not a state a listing can be in — some photo
     *  has to be it — so the way to change the cover is to name the new one. */
    isPrimary: z.literal(true).optional(),
  })
  .refine((value) => value.alt !== undefined || value.isPrimary !== undefined, {
    message: "Nothing to change.",
  });

export type MediaUpdateInput = z.infer<typeof mediaUpdateSchema>;

/** Bound on how many file parts one request may carry, enforced before any of
 *  them is inspected. */
export const MAX_UPLOAD_FILES = MAX_FILES_PER_UPLOAD;
